name: Unit tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: restore
        run: |
          apt-get install -y libgtest-dev
      - name: build
        run: .build/build
      - name: unittest
        run: .build/run-unittest
