name: Unit tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore
        run: |
          sudo apt-get install -y libgtest-dev
      - name: build
        run: .build/build
      - name: unittest
        run: .build/run-unittest

  # Builds and runs tests on Ubuntu 7.10.
  # It ships with:
  #
  # gcc (GCC) 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)
  # Copyright (C) 2006 Free Software Foundation, Inc.
  #
  # cmake version 2.4-patch 7
  #
  # This one is challenging:
  #
  # * For gcc, vast majority of C++11 features are missing from this release (many were added around GCC 4.3 and 4.4).
  #   Some C99 features are also missing. C++98 support seems to be full-featued.
  #
  # * Modern GTest doesn't work in this environment, as GTest v1.12.x requires C++11 and modern GTest v1.13+ requires C++14.
  #   To work around this, we supply nano substitute of GTest (tests/gtest-nano.h), partially compatible with API.
  #
  # * CMake is way too old to be usable without major rewrite of all the CMakeLists.txt to use ancient/deprecated syntax.
  #   To work around this, we use plain GNU make(1) and supply custom Makefile.gcc4.
  linux_ubuntu_7_10:
    runs-on: ubuntu-latest
    container:
      image: icomputer7/ancient-ubuntu-docker:gutsy
    steps:
      - name: restore
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install \
              git \
              make \
              g++
      - uses: actions/checkout@v3
      - name: build
        run: make -f Makefile.gcc4
      - name: unittest
        run: build/unittest

  windows:
    runs-on: windows-latest
    # NB: see https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md for what's available in this image
    steps:
      - uses: actions/checkout@v3
      - name: restore
        run: |
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg install gtest:x64-windows
      - name: build
        run: .build\build.ps1 -GTestPath C:\vcpkg\installed\x64-windows
      - name: unittest
        run: .build\run-unittest.ps1
