name: Unit tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore
        run: |
          sudo apt-get install -y libgtest-dev
      - name: build
        run: .build/build
      - name: unittest
        run: .build/run-unittest

  windows-msvc:
    runs-on: windows-latest
    # NB: see https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md for what's available in this image
    steps:
      - uses: actions/checkout@v3
      - name: restore
        run: |
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg install gtest:x64-windows
      - name: build
        run: .build\build-msvc.ps1 -GTestPath C:\vcpkg\installed\x64-windows
      - name: unittest
        run: .build\run-unittest.ps1

  windows-mingw64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: restore
        run: |
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg install gtest:x64-windows
      - name: build
        run: .build\build-mingw.ps1 -GTestPath C:\vcpkg\installed\x64-windows
      - name: unittest
        run: .build\run-unittest.ps1
